Repository metrotranscom/doorway, pull requests merged in 2023-08, with the labels that each got.

#275 fix: skip map link
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/components/listings/ListingsCombined.module.scss
  sites/public/src/components/listings/ListingsList.tsx
  sites/public/src/components/listings/ListingsMap.tsx
Labels: ready to merge

#284 fix: align questions to left
  doorway-ui-components/src/actions/DoorwayCollapsibleSection.tsx
  yarn.lock
Labels: ready to merge

#285 fix: highlight help center nav item when selected
  doorway-ui-components/src/headers/SiteHeader.tsx
  sites/public/src/lib/helpers.tsx
Labels: ready to merge

#288 fix: align checkboxes
  doorway-ui-components/src/forms/FieldGroup.scss
  sites/public/src/components/listings/search/LandingSearch.tsx
  sites/public/src/components/listings/search/ListingsSearchModal.tsx
Labels: ready to merge

#290 fix: partners portal misaligned footer
  doorway-ui-components/src/footers/SiteFooter.scss
  doorway-ui-components/src/footers/SiteFooter.tsx
  doorway-ui-components/src/navigation/FooterNav.scss
  doorway-ui-components/src/navigation/FooterNav.tsx
  doorway-ui-components/src/sections/FooterSection.scss
  doorway-ui-components/src/sections/FooterSection.tsx
  sites/partners/__tests__/pages/listings/index.test.tsx
  sites/partners/__tests__/pages/users/index.test.tsx
  sites/partners/src/layouts/index.tsx
Labels: ready to merge

#289 fix: rent formatting hack
  sites/public/src/components/listings/search/LandingSearch.tsx
  sites/public/src/components/listings/search/ListingsSearchModal.tsx
Labels: on hold

#271 fix: cypress tests
  .github/workflows/cypress_partners.yml
  .github/workflows/cypress_public.yml
  .github/workflows/integration_tests.yml
  .github/workflows/lint.yml
  .github/workflows/unit_tests_backend_core.yml
  .github/workflows/unit_tests_doorway_ui_components.yml
  .github/workflows/unit_tests_shared_helpers.yml
  .github/workflows/unit_tests_sites_partners.yml
  .github/workflows/unit_tests_sites_public.yml
  backend/core/.env.template
  backend/core/src/app.module.ts
  backend/core/src/seeder/seed.ts
  doorway-ui-components/src/headers/DoorwayHero.tsx
  sites/partners/cypress.config.ts
  sites/partners/cypress/e2e/03-listing.spec.ts
  sites/partners/cypress/e2e/06-admin-user-mangement.spec.ts
  sites/partners/cypress/e2e/07-jurisdictional-admin-user-management.spec.ts
  sites/partners/cypress/e2e/08-preference-management.spec.ts
  sites/partners/cypress/fixtures/createJurisdictionalAdminUser.json
  sites/partners/cypress/fixtures/createJurisdictionalAdminUser2.json
  sites/partners/cypress/fixtures/createPartnerUser.json
  sites/partners/cypress/fixtures/createPartnerUser2.json
  sites/partners/cypress/fixtures/jurisdictionalAdmin.json
  sites/partners/package.json
  sites/partners/src/lib/listings/formTypes.ts
  sites/public/cypress.config.ts
  sites/public/cypress/e2e/pages/my-applications.spec.ts
  sites/public/cypress/e2e/pages/submit-application.spec.ts
  sites/public/package.json
  sites/public/src/components/applications/ValidateAddress.tsx
  sites/public/src/pages/applications/contact/alternate-contact-contact.tsx
  sites/public/src/pages/applications/contact/alternate-contact-name.tsx
  sites/public/src/pages/applications/financial/vouchers.tsx
  sites/public/src/pages/applications/household/ada.tsx
  sites/public/src/pages/applications/household/add-members.tsx
  sites/public/src/pages/applications/household/changes.tsx
  sites/public/src/pages/applications/household/member.tsx
  sites/public/src/pages/applications/household/members-info.tsx
  sites/public/src/pages/applications/household/preferred-units.tsx
  sites/public/src/pages/applications/household/student.tsx
  sites/public/src/pages/applications/review/confirmation.tsx
  sites/public/src/pages/applications/start/autofill.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
  sites/public/src/pages/applications/view.tsx
  tasks/import-listings/package.json
Labels: ready to merge

#309 Release/2023 08 16
  .eslintrc.js
  backend/core/src/email/email.service.ts
  backend/core/src/listings/cache-purge.service.ts
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/types/listing-status-enum.ts
  backend/core/src/listings/validation-pipes/listing-create-validation-pipe.ts
  backend/core/src/listings/validation-pipes/listing-update-validation-pipe.ts
  backend/core/src/migration/1691377869351-new-status-fields.ts
  backend/core/src/migration/1691438164033-user-req-changes.ts
  backend/core/types/src/backend-swagger.ts
  doorway-ui-components/src/blocks/ImageCard.tsx
  doorway-ui-components/src/helpers/useFallbackImage.ts
  shared-helpers/package.json
  shared-helpers/src/utilities/photos.ts
  sites/partners/.env.template
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/next.config.js
  sites/partners/package.json
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/Aside.tsx
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/ListingStatusBar.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/settings/ManageIconSection.tsx
  sites/partners/src/components/shared/StatusBar.tsx
  sites/partners/src/pages/application/[id]/index.tsx
  sites/partners/src/pages/index.tsx
  sites/partners/src/pages/listings/[id]/index.tsx
  sites/partners/src/pages/users/index.tsx
  sites/public/.env.template
  sites/public/.gitignore
  sites/public/next.config.js
  sites/public/package.json
  sites/public/public/images/listing-fallback.png
  sites/public/sentry.client.config.ts
  sites/public/sentry.edge.config.ts
  sites/public/sentry.server.config.ts
  sites/public/src/components/listing/ListingView.tsx
  sites/public/src/lib/helpers.tsx
  sites/public/src/pages/api/sentry-example-api.js
  sites/public/src/pages/sentry-example-page.js
  sites/public/tsconfig.json
  yarn.lock
Labels: 1 review needed

#315 fix: add 120% ami info
  backend/core/src/migration/1692890494691-ami-120-updates.ts
Labels: ready to merge

#310 fix: homepage layout alignment
  doorway-ui-components/src/headers/DoorwayHero.scss
  sites/public/src/components/listings/search/LandingSearch.module.scss
  sites/public/src/components/listings/search/LandingSearch.tsx
Labels: ready to merge

#320 fix: change ami update migration
  backend/core/src/migration/1692890494691-ami-120-updates.ts
  sites/public/cypress/e2e/pages/submit-application.spec.ts
Labels: ready to merge
