Repository metrotranscom/doorway, pull requests merged in 2024-11, with the labels that each got.

#927 fix: add correct error message for outdated password
  api/src/passports/jwt.strategy.ts
  api/test/unit/passports/jwt.strategy.spec.ts
Labels: ready to merge

#918 release: update ami chart script (#4408)
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/ami-chart-update-import.dto.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release

#921 release: map marker endpoint (#4453)
  api/src/controllers/listing.controller.ts
  api/src/dtos/listings/listing-map-marker.dto.ts
  api/src/services/listing.service.ts
  api/test/integration/api-key-guard.e2e-spec.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release

#893 fix: applying pass key to endpoints that were missing it (#4374)
  api/src/controllers/auth.controller.ts
  api/src/controllers/lottery.controller.ts
  api/src/controllers/script-runner.controller.ts
Labels: ready to merge, release

#928 fix: skip autofill if no applicant data
  sites/public/src/pages/applications/start/autofill.tsx
Labels: ready to merge

#929 fix: fixes casbin error
  api/package.json
Labels: high priority, ready to merge

#930 fix: no more ^
  api/yarn.lock
Labels: ready to merge

#922 fix: listing duplicate fe (#4309)
  api/.env.template
  api/package.json
  api/prisma/migrations/19_duplicate_listing_permissions/migration.sql
  api/prisma/migrations/20_dwy_limited_juris_enum/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-helpers/jurisdiction-factory.ts
  api/prisma/seed-staging.ts
  api/src/dtos/jurisdictions/jurisdiction.dto.ts
  api/src/services/listing.service.ts
  api/test/integration/jurisdiction.e2e-spec.ts
  api/test/integration/permission-tests/helpers.ts
  api/yarn.lock
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/.env.template
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/next.config.js
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/CopyListingDialog.tsx
  sites/partners/src/components/users/ReRequestConfirmation.tsx
  sites/partners/src/pages/index.tsx
  sites/partners/src/pages/listings/[id]/index.tsx
  sites/partners/src/pages/settings/index.tsx
Labels: ready to merge

#932 fix: dwy specific env setup
  .github/workflows/cypress_partners.yml
  build/docker/Dockerfile.sites-generic
  ci/buildspec/build_partners.yml
Labels: ready to merge

#926 fix: removal references to smc
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/tsx_content/get-started-cards.tsx
Labels: ready to merge

#912 fix: dependabot updates
  api/src/services/listing.service.ts
  api/yarn.lock
  doorway-ui-components/.circleci/config.yml
  doorway-ui-components/package.json
  shared-helpers/src/auth/catchNetworkError.ts
  sites/partners/package.json
  sites/public/.env.template
  sites/public/package.json
  yarn.lock
Labels: ready to merge, release

#947 feat: create feature flag table (#4475)
  api/prisma/migrations/20_create_feature_flag_table/migration.sql
  api/prisma/schema.prisma
Labels: ready to merge, release

#948 fix: set publishedAt during create
  api/src/services/listing.service.ts
  api/test/unit/services/listing.service.spec.ts
Labels: ready to merge

#944 fix: update retract modal copy
  sites/partners/page_content/locale_overrides/general.json
Labels: ready to merge, release

#951 fix: add conditional rendering
  sites/partners/src/pages/listings/[id]/applications/index.tsx
Labels: ready to merge

#949 fix: return updated failed login attempts (#4474)
  api/src/passports/mfa.strategy.ts
  api/src/passports/single-use-code.strategy.ts
  api/src/utilities/passport-validator-utilities.ts
  api/test/unit/passports/passport-validator-utilities.spec.ts
Labels: ready to merge, release

#911 fix: hide other recipients
  api/src/services/email.service.ts
  api/src/services/listing.service.ts
  api/src/services/lottery.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/unit/services/email.service.spec.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  yarn.lock
Labels: ready to merge

#955 fix: remove opt in logic
  api/src/utilities/lottery-date-validator.ts
  api/test/unit/utilities/lottery-date-validator.spec.ts
Labels: ready to merge

#953 fix: remove env variable dependencies from tests (#4471)
  .circleci/config.yml
  api/test/integration/api-key-guard.e2e-spec.ts
  api/test/integration/auth.e2e-spec.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/integration/throttle-guard.e2e-spec.ts
  api/test/integration/user.e2e-spec.ts
  api/test/unit/passports/jwt.strategy.spec.ts
  api/test/unit/passports/mfa.strategy.spec.ts
  api/test/unit/passports/single-use-code.strategy.spec.ts
  api/test/unit/services/auth.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  api/test/unit/services/user.service.spec.ts
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/e2e/default/09-lottery.spec.ts
  sites/partners/cypress/fixtures/address.json
  sites/partners/cypress/fixtures/cypressUpload.json
Labels: ready to merge

#960 fix: handle copying app methods (#4491)
  api/src/services/listing.service.ts
Labels: ready to merge

#940 release: date field improvements and application due date
  api/src/dtos/listings/listing-published-update.dto.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  doorway-ui-components/package.json
  shared-helpers/package.json
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/fixtures/minimalListing.json
  sites/partners/cypress/support/commands.js
  sites/partners/package.json
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormApplicationData.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/partners/src/lib/listings/formTypes.ts
  sites/public/package.json
  sites/public/src/pages/applications/review/confirmation.tsx
  yarn.lock
Labels: ready to merge
