Repository metrotranscom/doorway, pull requests merged in 2024-10, with the labels that each got.

#863 release: history log fix
  api/src/services/lottery.service.ts
  api/test/unit/services/lottery.service.spec.ts
Labels: ready to merge, release

#866 fix: dont send lottery emails to duplicate applications (#4346)
  api/src/services/listing.service.ts
  api/src/services/lottery.service.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/unit/services/lottery.service.spec.ts
Labels: ready to merge, release

#867 feat: switching to write stream and sequential building (#4329)
  api/src/services/application-exporter.service.ts
Labels: ready to merge, release

#831 feat: require terms and conditions acceptance at log-in
  api/prisma/seed-helpers/user-factory.ts
  api/prisma/seed-staging.ts
  api/src/controllers/auth.controller.ts
  api/src/dtos/auth/login-single-use-code.dto.ts
  api/src/dtos/auth/login.dto.ts
  api/src/dtos/auth/update-password.dto.ts
  api/src/passports/single-use-code.strategy.ts
  api/src/services/auth.service.ts
  api/test/integration/auth.e2e-spec.ts
  api/test/unit/passports/single-use-code.strategy.spec.ts
  api/test/unit/services/auth.service.spec.ts
  shared-helpers/src/auth/AuthContext.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/public/src/components/shared/TermsModal.tsx
  sites/public/src/pages/create-account.tsx
  sites/public/src/pages/reset-password.tsx
  sites/public/src/pages/sign-in.tsx
  sites/public/src/pages/verify.tsx
Labels: ready to merge

#855 fix: update lottery banner content
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge

#845 fix: set workAddress to undefined
  api/src/services/application.service.ts
  api/test/unit/services/application.service.spec.ts
  sites/public/src/lib/applications/appAutofill.ts
Labels: ready to merge

#842 feat: add various content updates
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/tsx_content/get-started-cards.tsx
Labels: ready to merge

#854 fix: convert single quote entities in Opportunities email
  api/src/services/email.service.ts
  api/src/views/listing-opportunity.hbs
Labels: ready to merge

#759 fix: add user and application import scripts
  api/src/controllers/script-runner.controller.ts
  api/src/services/auth.service.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/auth.service.spec.ts
  api/test/unit/services/script-runner.service.spec.ts
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsAddressColumns.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsPrimaryApplicant.tsx
  sites/partners/src/pages/application/[id]/index.tsx
Labels: 1 review needed, needs changes

#878 fix: match pref on id (#4372)
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
Labels: ready to merge, release

#884 release: record of listing copy (#4375)
  api/prisma/migrations/18_copy_of_reference/migration.sql
  api/prisma/schema.prisma
  api/src/services/listing-csv-export.service.ts
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
Labels: ready to merge, release

#881 fix: household members link on application review (#4385)
  sites/public/cypress/support/commands.js
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/pages/applications/household/add-members.tsx
Labels: ready to merge, release

#885 fix: may the force be with you (#4388)
  api/package.json
Labels: ready to merge, release

#882 fix: add required field for applications in script
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
Labels: 1 review needed

#880 chore: depcheck and missing deps - doorway uic
  doorway-ui-components/.storybook/main.js
  doorway-ui-components/__tests__/page_components/ListingMap.test.tsx
  doorway-ui-components/index.ts
  doorway-ui-components/package.json
  doorway-ui-components/src/page_components/listing/ListingMap.scss
  doorway-ui-components/src/page_components/listing/ListingMap.stories.tsx
  doorway-ui-components/src/page_components/listing/ListingMap.tsx
  sites/public/package.json
  sites/public/src/pages/applications/start/autofill.tsx
  yarn.lock
Labels: ready to merge

#886 fix: script runner for new reserved community type (#4380)
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/community-type.dto.ts
  api/src/services/script-runner.service.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
Labels: ready to merge

#901 release: flaky backend tests (#4389)
  api/src/dtos/users/confirmation-request.dto.ts
  api/test/integration/application.e2e-spec.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/integration/user.e2e-spec.ts
  api/test/unit/services/auth.service.spec.ts
Labels: ready to merge, release

#902 feat: exposes pref unit type (#4401)
  api/src/services/application.service.ts
Labels: ready to merge, release

#904 refactor: postcss vulnerability and cleanup
  .dockerignore
  .eslintrc.js
  .gitignore
  api/package.json
  api/yarn.lock
  doorway-ui-components/.github/workflows/release.yml
  doorway-ui-components/.gitignore
  doorway-ui-components/.npmignore
  doorway-ui-components/.releaserc.json
  doorway-ui-components/.storybook/constants.ts
  doorway-ui-components/.storybook/main.js
  doorway-ui-components/.storybook/next-link.js
  doorway-ui-components/.storybook/preview-body.html
  doorway-ui-components/.storybook/preview-head.html
  doorway-ui-components/.storybook/preview.ts
  doorway-ui-components/V2Styles.md
  doorway-ui-components/package.json
  doorway-ui-components/scripts/duplicate-translations.ts
  doorway-ui-components/scripts/generate-translations.ts
  doorway-ui-components/scripts/missing-translations.ts
  doorway-ui-components/scripts/reformat-strings.ts
  doorway-ui-components/scripts/unused-foreign-keys.ts
  doorway-ui-components/src/actions/Button.docs.mdx
  doorway-ui-components/src/actions/Button.stories.tsx
  doorway-ui-components/src/actions/ButtonGroup.docs.mdx
  doorway-ui-components/src/actions/ButtonGroup.stories.tsx
  doorway-ui-components/src/blocks/ActionBlock.stories.tsx
  doorway-ui-components/src/blocks/Card.docs.mdx
  doorway-ui-components/src/blocks/Card.stories.tsx
  doorway-ui-components/src/blocks/ImageCard.docs.mdx
  doorway-ui-components/src/blocks/ImageCard.stories.tsx
  doorway-ui-components/src/documentation/Utilities.scss
  doorway-ui-components/src/documentation/Utilities.stories.mdx
  doorway-ui-components/src/documentation/Utilities.tsx
  doorway-ui-components/src/footers/SiteFooter.stories.tsx
  doorway-ui-components/src/forms/Field.stories.tsx
  doorway-ui-components/src/forms/FieldGroup.stories.tsx
  doorway-ui-components/src/headers/SiteHeader.stories.tsx
  doorway-ui-components/src/navigation/LanguageNav.stories.tsx
  doorway-ui-components/src/overlays/Modal.docs.mdx
  doorway-ui-components/src/overlays/Modal.stories.tsx
  doorway-ui-components/src/page_components/listing/ContentAccordion.stories.tsx
  doorway-ui-components/src/page_components/listing/ListingCard.docs.mdx
  doorway-ui-components/src/page_components/listing/ListingCard.stories.tsx
  doorway-ui-components/yarn.lock
  sites/public/package.json
  yarn.lock
Labels: ready to merge

#872 fix: change begin to language name
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/pages/applications/start/choose-language.tsx
Labels: release

#903 fix: exposing more closed listings (#4402)
  sites/public/.env.template
  sites/public/next.config.js
  sites/public/src/lib/hooks.ts
Labels: ready to merge, release

#908 fix: updated email and logic for single use code (#4376)
  api/prisma/seed-helpers/translation-factory.ts
  api/src/controllers/script-runner.controller.ts
  api/src/passports/mfa.strategy.ts
  api/src/passports/single-use-code.strategy.ts
  api/src/services/auth.service.ts
  api/src/services/email.service.ts
  api/src/services/script-runner.service.ts
  api/src/services/user.service.ts
  api/src/utilities/generate-single-use-code.ts
  api/src/utilities/get-single-use-code.ts
  api/src/utilities/passport-validator-utilities.ts
  api/test/unit/services/auth.service.spec.ts
  api/test/unit/services/user.service.spec.ts
  api/test/unit/utilities/generate-single-use-code.spec.ts
  api/test/unit/utilities/get-single-use-code.spec.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
Labels: ready to merge, release

#900 fix: cleanup lint warnings (#4404)
  api/src/controllers/reserved-community-type.controller.ts
  api/src/dtos/applications/demographic.dto.ts
  api/src/dtos/applications/public-apps-count.dto.ts
  api/src/dtos/applications/public-apps-filtered.dto.ts
  api/src/dtos/applications/public-apps-view-params.dto.ts
  api/src/dtos/applications/public-apps-view-response.dto.ts
  api/src/logger/winston.logger.ts
  api/src/services/script-runner.service.ts
  api/src/services/translation.service.ts
  api/src/utilities/lottery-date-validator.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/unit/services/asset.service.spec.ts
  api/test/unit/services/email.service.spec.ts
  api/test/unit/services/google-translate.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  api/test/unit/utilities/lottery-date-validator.spec.ts
  package.json
  shared-helpers/src/views/CustomIcons.tsx
  shared-helpers/src/views/forgot-password/FormForgotPassword.tsx
  sites/partners/__tests__/components/listings/PaperListingForm/sections/LotteryResults.test.tsx
  sites/partners/src/components/applications/ApplicationsColDefs.ts
  sites/partners/src/components/listings/PaperListingForm/dialogs/RequestChangesDialog.tsx
  sites/partners/src/components/shared/NavigationHeader.tsx
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/partners/src/pages/listings/[id]/edit.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
  sites/public/__tests__/pages/applications/review/demographics.test.tsx
  sites/public/cypress/support/commands.js
  sites/public/src/components/account/ConfirmationModal.tsx
  sites/public/src/lib/applications/appAutofill.ts
  sites/public/src/pages/applications/household/add-members.tsx
  sites/public/src/pages/applications/preferences/general.tsx
  sites/public/src/pages/create-account.tsx
  sites/public/src/pages/reset-password.tsx
  sites/public/src/pages/sign-in.tsx
  sites/public/src/pages/verify.tsx
  yarn.lock
Labels: ready to merge, release

#915 fix: split out scripts and fix public transfer script
  api/src/controllers/script-runner.controller.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#917 feat: senior veteran community type
  doorway-ui-components/src/locales/general.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
Labels: ready to merge

#916 refactor: homepage updates
  doorway-ui-components/__tests__/footers/SiteFooter.test.tsx
  doorway-ui-components/__tests__/navigation/FooterNav.test.tsx
  doorway-ui-components/__tests__/sections/FooterSection.test.tsx
  doorway-ui-components/index.ts
  doorway-ui-components/src/footers/SiteFooter.scss
  doorway-ui-components/src/footers/SiteFooter.tsx
  doorway-ui-components/src/navigation/FooterNav.scss
  doorway-ui-components/src/navigation/FooterNav.tsx
  doorway-ui-components/src/sections/FooterSection.scss
  doorway-ui-components/src/sections/FooterSection.tsx
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/public/images/linkedin-logo.svg
  sites/public/public/images/youtube-logo.svg
  sites/public/src/components/shared/CustomSiteFooter.module.scss
  sites/public/src/components/shared/CustomSiteFooter.tsx
  sites/public/src/layouts/application.tsx
  sites/public/src/lib/helpers.tsx
  sites/public/src/pages/index.tsx
  sites/public/styles/overrides.scss
Labels: ready to merge

#914 feat: adding private backend service
  ci/buildspec/migrate_stop_backend.yml
  ci/buildspec/update_ecs.yml
Labels: 1 review needed

#871 feat: add additional content for lottery published email
  api/prisma/seed-helpers/translation-factory.ts
  api/src/controllers/script-runner.controller.ts
  api/src/services/email.service.ts
  api/src/services/script-runner.service.ts
  api/src/views/lottery-published-applicant.hbs
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: 1 review needed

#905 fix: add additional content for confirmation email
  api/prisma/seed-helpers/translation-factory.ts
  api/src/services/email.service.ts
  api/src/services/script-runner.service.ts
  api/src/views/confirmation.hbs
  api/test/unit/services/email.service.spec.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/pages/applications/review/confirmation.tsx
Labels: blocked
