Repository metrotranscom/doorway, pull requests merged in 2024-05, with the labels that each got.

#593 fix: isCommonApp approach
  sites/public/src/components/listing/ListingView.tsx
Labels: ready to merge

#598 fix: Underline Terms of Use Links
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
Labels: ready to merge

#603 fix: network error updates
  shared-helpers/src/auth/catchNetworkError.ts
Labels: ready to merge

#611 fix: versioning issue
  sites/partners/package.json
  yarn.lock
Labels: ready to merge

#606 fix: translation fixes
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/partners/page_content/locale_overrides/general.json
  sites/public/page_content/locale_overrides/general.json
Labels: ready to merge

#608 fix: remove form field titles
  doorway-ui-components/package.json
  shared-helpers/package.json
  sites/partners/package.json
  sites/public/package.json
  yarn.lock
Labels: ready to merge

#619 597/error message matching
  shared-helpers/src/auth/catchNetworkError.ts
Labels: ready to merge

#620 fix: domain fix for doorway
  api/.env.template
  api/src/services/auth.service.ts
Labels: P0, ready to merge

#616 feat: expire app data
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/partners/styles/applications.module.scss
Labels: ready to merge

#629 fix: missing string
  sites/public/src/pages/applications/financial/vouchers.tsx
Labels: ready to merge

#633 Fix: Edit Application Fails to Render
  sites/partners/src/lib/applications/formatApplicationData.ts
Labels: ready to merge

#635 Fix: Agree To Terms Saves Correctly
  sites/public/src/pages/applications/review/terms.tsx
Labels: ready to merge

#641 feat: release - filter flagged duplicate sets (#4097)
  api/src/dtos/application-flagged-sets/afs-query-params.dto.ts
  api/src/services/application-flagged-set.service.ts
  api/test/unit/services/application-flagged-set.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/lib/helpers.test.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/applications/ApplicationsColDefs.ts
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx
  sites/partners/src/lib/helpers.ts
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/application/[id]/applicationsCols.tsx
  sites/partners/src/pages/index.tsx
  sites/partners/src/pages/listings/[id]/applications/pending/index.tsx
  sites/partners/src/pages/listings/[id]/applications/resolved/index.tsx
Labels: ready to merge

#643 feat: new application index on user_id (#4098)
  api/prisma/migrations/20240520173759_application_user_id_index/migration.sql
  api/prisma/schema.prisma
Labels: ready to merge

#646 fix: adding pass key info to public partners
  build/docker/Dockerfile.sites-generic
  ci/buildspec/build_partners.yml
  ci/buildspec/build_public.yml
Labels: 1 review needed

#648 feat: makes the pass key a contingent header
  sites/partners/src/pages/api/adapter/[...backendUrl].ts
  sites/partners/src/pages/api/adapter/upload.ts
  sites/partners/src/pages/listings/[id]/edit.tsx
  sites/partners/src/pages/listings/[id]/index.tsx
  sites/public/src/lib/hooks.ts
  sites/public/src/pages/api/adapter/[...backendUrl].ts
  sites/public/src/pages/listing/[id].tsx
  sites/public/src/pages/listing/[id]/[slug].tsx
  sites/public/src/pages/preview/listings/[id].tsx
Labels: ready to merge

#650 fix: broader lat long matching
  sites/partners/cypress/e2e/default/03-listing.spec.ts
Labels: ready to merge

#644 fix: match import with app file
  shared-helpers/src/auth/Timeout.tsx
Labels: ready to merge

#647 fix: partner and public matching (#4090)
  api/src/services/user.service.ts
  api/test/integration/user.e2e-spec.ts
  api/test/unit/services/user.service.spec.ts
Labels: ready to merge

#657 release: Demographics Race Field Render Issue
  shared-helpers/src/utilities/formKeys.ts
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormDemographics.tsx
  sites/public/src/pages/applications/review/demographics.tsx
Labels: ready to merge
