Repository metrotranscom/doorway, pull requests merged in 2024-12, with the labels that each got.

#968 release: feature flag consumption
  api/prisma/seed-helpers/feature-flag-factory.ts
  api/src/controllers/feature-flag.controller.ts
  api/src/dtos/feature-flags/feature-flag-associate.dto.ts
  api/src/dtos/feature-flags/feature-flag-create.dto.ts
  api/src/dtos/feature-flags/feature-flag-update.dto.ts
  api/src/dtos/feature-flags/feature-flag.dto.ts
  api/src/dtos/jurisdictions/jurisdiction-update.dto.ts
  api/src/dtos/jurisdictions/jurisdiction.dto.ts
  api/src/modules/app.module.ts
  api/src/modules/feature-flag.module.ts
  api/src/permission-configs/permission_policy.csv
  api/src/services/feature-flag.service.ts
  api/src/services/jurisdiction.service.ts
  api/test/integration/feature-flag.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/unit/services/feature-flag.service.spec.ts
  api/test/unit/services/jurisdiction.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release

#964 docs: update readmes
  README.md
  api/.env.template
  api/README.md
  shared-helpers/README.md
  sites/partners/README.md
  sites/public/README.md
Labels: ready to merge, release

#973 fix: check for limited juris role
  sites/partners/src/pages/listings/[id]/index.tsx
Labels: ready to merge

#956 fix: remove contact preferences
  api/src/enums/applications/household-member-relationship-enum.ts
  api/src/utilities/application-export-helpers.ts
  api/test/unit/services/application-exporter.service.spec.ts
  api/test/unit/utilities/application-export-helpers.spec.ts
  doorway-ui-components/src/locales/es.json
  doorway-ui-components/src/locales/general.json
  doorway-ui-components/src/locales/tl.json
  doorway-ui-components/src/locales/vi.json
  doorway-ui-components/src/locales/zh.json
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/utilities/blankApplication.ts
  shared-helpers/src/utilities/formKeys.ts
  sites/partners/cypress/fixtures/alternateContactOnlyData.json
  sites/partners/cypress/fixtures/applicantOnlyData.json
  sites/partners/cypress/fixtures/application.json
  sites/partners/cypress/fixtures/demographicsOnlyData.json
  sites/partners/cypress/fixtures/emptyApplication.json
  sites/partners/cypress/fixtures/householdDetailsOnlyData.json
  sites/partners/cypress/fixtures/householdIncomeOnlyData.json
  sites/partners/cypress/fixtures/householdMemberOnlyData.json
  sites/partners/cypress/fixtures/partialApplicationA.json
  sites/partners/cypress/support/commands.js
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsPrimaryApplicant.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/CopyListingDialog.tsx
  sites/partners/src/lib/applications/FormTypes.ts
  sites/partners/src/lib/applications/formatApplicationData.ts
  sites/public/__tests__/pages/applications/contact/address.test.tsx
  sites/public/cypress/mockData/applicationData.ts
  sites/public/cypress/support/commands.js
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/lib/helpers.tsx
  sites/public/src/pages/applications/contact/address.tsx
Labels: ready to merge

#979 fix: partial date formatting on paper app
  sites/partners/src/lib/applications/formatApplicationData.ts
Labels: ready to merge

#978 fix: paper application saving issue
  api/src/controllers/script-runner.controller.ts
  api/src/services/application.service.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/src/lib/applications/formatApplicationData.ts
Labels: bug, high priority, ready to merge

#981 fix: timezone apply to opp email
  api/src/services/email.service.ts
Labels: high priority, ready to merge

#989 fix: batch deletion for remove work address script
  api/src/services/application.service.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/application.service.spec.ts
  api/test/unit/services/script-runner.service.spec.ts
Labels: ready to merge

#970 feat: add mtc logo to the top nav, remove from footer
  doorway-ui-components/src/headers/SiteHeader.scss
  doorway-ui-components/src/navigation/LanguageNav.scss
  doorway-ui-components/src/navigation/LanguageNav.tsx
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/public/images/mtc-abag-logo.png
  sites/public/src/components/shared/CustomSiteFooter.tsx
  sites/public/styles/overrides.scss
Labels: ready to merge

#991 release: building selection criteria adjustment
  api/src/services/listing.service.ts
Labels: ready to merge

#1006 feat: before app submission refresh access token
  shared-helpers/src/auth/Timeout.tsx
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/pages/applications/review/terms.tsx
Labels: high priority, 1 review needed

#1017 fix: turn off autofill
  sites/public/src/pages/applications/start/autofill.tsx
Labels: ready to merge

#1015 fix: partners seeing all listings in list
  api/src/controllers/listing.controller.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/index.tsx
Labels: ready to merge

#1011 fix: make drawer accessible in mobile landscape
  doorway-ui-components/src/headers/SiteHeader.scss
  sites/public/cypress/support/commands.js
  sites/public/src/components/listings/ListingsCombined.module.scss
  sites/public/src/components/listings/ListingsCombinedDeprecated.module.scss
  sites/public/src/components/listings/ListingsCombinedDeprecated.tsx
  sites/public/src/components/listings/search/ListingsSearch.module.scss
  sites/public/src/components/listings/search/ListingsSearchDeprecated.module.scss
  sites/public/src/components/listings/search/ListingsSearchMetadataDeprecated.tsx
  sites/public/src/layouts/application.tsx
Labels: ready to merge

#1023 fix: set optOut watch default value (#4512)
  sites/partners/src/components/settings/PreferenceDrawer.tsx
Labels: ready to merge

#1010 fix: ami chart selection bug
  api/prisma/seed-staging.ts
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
Labels: ready to merge
