Repository metrotranscom/doorway, pull requests merged in 2024-09, with the labels that each got.

#801 feat: save and continue (#4256)
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/e2e/listings-approval/listings-approval.spec.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/CloseListingDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/ListingApprovalDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/LiveConfirmationDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/PublishListingDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/RequestChangesDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/SaveBeforeExitDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/pages/listings/[id]/edit.tsx
Labels: ready to merge, release

#800 fix: include comparison in next config (#4274)
  sites/partners/next.config.js
  sites/partners/src/components/shared/NavigationHeader.tsx
  sites/partners/src/pages/listings/[id]/applications/index.tsx
Labels: ready to merge, release

#813 feat: release lottery apps fe 2
  api/prisma/migrations/16_add_lottery_last_published_at/migration.sql
  api/prisma/schema.prisma
  api/src/controllers/application.controller.ts
  api/src/dtos/applications/public-apps-count.dto.ts
  api/src/dtos/applications/public-apps-filtered.dto.ts
  api/src/dtos/applications/public-apps-view-params.dto.ts
  api/src/dtos/applications/public-apps-view-response.dto.ts
  api/src/dtos/listings/listing.dto.ts
  api/src/enums/applications/filter-enum.ts
  api/src/services/application.service.ts
  api/src/services/lottery.service.ts
  api/test/integration/application.e2e-spec.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/unit/services/application.service.spec.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  shared-helpers/package.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/package.json
  sites/public/.env.template
  sites/public/__tests__/components/applications/StatusItem.test.tsx
  sites/public/next.config.js
  sites/public/package.json
  sites/public/src/components/account/ApplicationsView.module.scss
  sites/public/src/components/account/ApplicationsView.tsx
  sites/public/src/components/account/StatusItem.tsx
  sites/public/src/components/account/StatusItemWrapper.tsx
  sites/public/src/pages/account/StatusItemWrapper.tsx
  sites/public/src/pages/account/account.module.scss
  sites/public/src/pages/account/applications.tsx
  sites/public/src/pages/account/applications/closed/index.tsx
  sites/public/src/pages/account/applications/index.tsx
  sites/public/src/pages/account/applications/lottery/index.tsx
  sites/public/src/pages/account/applications/open/index.tsx
  sites/public/styles/overrides.scss
  yarn.lock
Labels: ready to merge, release

#818 feat: add data viz banner
  doorway-ui-components/src/blocks/ActionBlock.scss
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/.env.template
  sites/public/next.config.js
  sites/public/src/pages/index.tsx
Labels: ready to merge

#821 fix: add releaseDate to partner card (#4315)(release)
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge, release

#816 release: listing duplication endpoint
  api/.env.template
  api/src/controllers/listing.controller.ts
  api/src/dtos/listings/listing-duplicate.dto.ts
  api/src/services/listing.service.ts
  api/src/services/lottery.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release

#804 feat: lottery help center content
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/tsx_content/questions-cards.tsx
Labels: ready to merge, blocked

#830 test: flaky cypress listing search (#4335)
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/e2e/default/09-lottery.spec.ts
  sites/partners/cypress/e2e/listings-approval/listings-approval.spec.ts
  sites/partners/cypress/support/commands.js
  sites/partners/cypress/support/index.d.ts
Labels: ready to merge, release

#840 fix: add missing env var
  ci/buildspec/build_partners.yml
Labels: ready to merge

#841 fix: missing expiry env var 2
  build/docker/Dockerfile.sites-generic
Labels: ready to merge

#823 fix: allows uploading lottery result update (#4295)
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
Labels: ready to merge, release

#832 fix: lottery export terms checkbox
  sites/partners/src/components/shared/ExportTermsDialog.tsx
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge

#843 fix: nonpartner lottery results can now be uploaded
  sites/partners/src/components/listings/ListingFormActions.tsx
Labels: ready to merge

#848 fix: add lottery help center links to lottery results
  sites/public/src/pages/account/application/[id]/lottery-results.tsx
Labels: ready to merge

#864 fix: faq page fix
  doorway-ui-components/src/page_components/help-center/DoorwayLinkableCardGroup.tsx
  sites/public/src/tsx_content/questions-cards.tsx
Labels: ready to merge
