Repository metrotranscom/doorway, pull requests merged in 2024-08, with the labels that each got.

#758 feat: paper applications - new fields
  api/prisma/migrations/20240722184200_add_paper_app_fields/migration.sql
  api/prisma/schema.prisma
  api/src/dtos/applications/application.dto.ts
  api/src/services/application-csv-export.service.ts
  api/test/unit/services/application-csv-export.service.spec.ts
  api/test/unit/services/application.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/cypress/fixtures/alternateContactOnlyData.json
  sites/partners/cypress/fixtures/applicantOnlyData.json
  sites/partners/cypress/fixtures/application.json
  sites/partners/cypress/fixtures/demographicsOnlyData.json
  sites/partners/cypress/fixtures/emptyApplication.json
  sites/partners/cypress/fixtures/householdDetailsOnlyData.json
  sites/partners/cypress/fixtures/householdIncomeOnlyData.json
  sites/partners/cypress/fixtures/householdMemberOnlyData.json
  sites/partners/cypress/fixtures/partialApplicationA.json
  sites/partners/cypress/support/commands.js
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsAddressColumns.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormApplicationData.tsx
  sites/partners/src/lib/applications/FormTypes.ts
  sites/partners/src/lib/applications/formatApplicationData.ts
Labels: ready to merge

#778 release: change email update copy
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
Labels: ready to merge, release

#780 feat: doorway infra release - banner
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/layouts/application.tsx
Labels: P0, ready to merge

#781 release: remove errant lottery copy
  sites/partners/__tests__/pages/listings/lottery.test.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge, release

#783 fix: radio preferences don't show description and geocoding fields (#3918)
  shared-helpers/src/views/multiselectQuestions.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
  sites/partners/src/lib/applications/formatApplicationData.ts
  sites/public/__tests__/pages/applications/preferences/all.test.tsx
  sites/public/src/components/applications/ApplicationMultiselectQuestionStep.tsx
Labels: ready to merge

#784 fix: update node to 18.20
  build/docker/Dockerfile.backend
Labels: ready to merge

#787 release: require lottery date time fields
  api/src/dtos/listings/listing-update.dto.ts
  api/src/dtos/listings/listing.dto.ts
  api/src/utilities/lottery-date-validator.ts
  api/test/unit/utilities/lottery-date-validator.spec.ts
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
Labels: ready to merge, release

#793 fix: alphabetize all string files
  doorway-ui-components/src/locales/es.json
  doorway-ui-components/src/locales/general.json
  doorway-ui-components/src/locales/tl.json
  doorway-ui-components/src/locales/vi.json
  doorway-ui-components/src/locales/zh.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/partners/page_content/locale_overrides/general.json
  sites/public/page_content/locale_overrides/general.json
Labels: ready to merge

#794 fix: z-index issues related to the filter bar
  sites/public/src/components/listings/search/ListingsSearch.module.scss
  sites/public/styles/overrides.scss
Labels: ready to merge

#797 release: opt out existing lotteries
  api/prisma/seed-helpers/listing-factory.ts
  api/prisma/seed-staging.ts
  api/src/controllers/script-runner.controller.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release

#792 fix: update length requirement and error messaging (#4261)
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/views/address/FormAddressAlternate.tsx
  shared-helpers/src/views/multiselectQuestions.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
  sites/public/src/pages/account/edit.tsx
  sites/public/src/pages/applications/contact/address.tsx
  sites/public/src/pages/applications/contact/alternate-contact-contact.tsx
  sites/public/src/pages/applications/contact/alternate-contact-name.tsx
  sites/public/src/pages/applications/contact/alternate-contact-type.tsx
  sites/public/src/pages/applications/contact/name.tsx
  sites/public/src/pages/applications/household/member.tsx
  sites/public/src/pages/create-account.tsx
Labels: ready to merge

#796 release: auto publish lotteries
  api/.env.template
  api/src/controllers/listing.controller.ts
  api/src/controllers/lottery.controller.ts
  api/src/services/email.service.ts
  api/src/services/listing.service.ts
  api/src/services/lottery.service.ts
  api/src/utilities/cron-job-starter.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge, release
