Repository metrotranscom/doorway, pull requests merged in 2024-02, with the labels that each got.

#461 feat: add translated buttons to listing opportunity mail template
  backend/core/src/email/email.service.spec.ts
  backend/core/src/email/email.service.ts
  backend/core/src/migration/1706548936939-listing-opportunity-translated-buttons.ts
  backend/core/src/shared/views/listing-opportunity.hbs
  backend/core/src/shared/views/partials/head.hbs
  sites/public/src/pages/listing/[id].tsx
Labels: ready to merge

#471 Feat: Upgrade various github actions to supported versions
  .github/workflows/codeql.yml
  .github/workflows/cypress_partners.yml
  .github/workflows/cypress_partners_la.yml
  .github/workflows/cypress_public.yml
  .github/workflows/etl.yml
  .github/workflows/integration_tests.yml
  .github/workflows/lint.yml
  .github/workflows/unit_tests_backend_core.yml
  .github/workflows/unit_tests_doorway_ui_components.yml
  .github/workflows/unit_tests_shared_helpers.yml
  .github/workflows/unit_tests_sites_partners.yml
  .github/workflows/unit_tests_sites_public.yml
  .github/workflows/version_packages.yml
  doorway-ui-components/.github/workflows/release.yml
Labels: ready to merge

#479 fix: shared-helpers tailwind config
  sites/public/tailwind.config.js
Labels: 1 review needed

#484 fix: minimal change approach
  shared-helpers/src/locales/general.json
  sites/partners/cypress/support/commands.js
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormDemographics.tsx
  sites/public/cypress/support/commands.js
  sites/public/src/pages/applications/review/demographics.tsx
Labels: ready to merge

#485 feat: add Please Specify text field for Spoken Language
  backend/core/src/applications/services/application-csv-exporter.service.ts
  shared-helpers/src/locales/general.json
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormDemographics.tsx
  sites/partners/src/lib/applications/formatApplicationData.ts
  sites/public/src/pages/applications/review/demographics.tsx
  sites/public/src/pages/applications/review/terms.tsx
Labels: ready to merge

#478 feat: modifications for upcoming prisma
  sites/public/src/pages/listing/ext/[id].tsx
  tasks/import-listings/src/etl/transform/map.ts
Labels: 1 review needed, prisma rewrite

#488 fix: map images correctly for external
  tasks/import-listings/src/etl/transform/map.ts
Labels: ready to merge
