Repository metrotranscom/doorway, pull requests merged in 2024-07, with the labels that each got.

#717 fix: search issues
  sites/public/src/pages/_app.tsx
Labels: ready to merge

#667 feat: new limited jurisdictional admin role
  api/prisma/migrations/09_enable_all_parter_demographics/migration.sql
  api/prisma/migrations/12_is_limited_jurisdictional_admin/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-dev.ts
  api/prisma/seed-helpers/user-factory.ts
  api/prisma/seed-staging.ts
  api/src/controllers/multiselect-question.controller.ts
  api/src/dtos/users/user-role.dto.ts
  api/src/enums/permissions/user-role-enum.ts
  api/src/guards/any-admin.guard.ts
  api/src/permission-configs/permission_policy.csv
  api/src/services/application-csv-export.service.ts
  api/src/services/listing-csv-export.service.ts
  api/src/services/permission.service.ts
  api/src/utilities/build-user-where.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
  api/test/unit/services/user-csv-export.service.spec.ts
  shared-helpers/src/auth/AuthContext.ts
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/utilities/formKeys.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/shared/ListingGuard.tsx
  sites/partners/src/components/users/FormUserManage.tsx
  sites/partners/src/components/users/JurisdictionAndListingSelection.tsx
  sites/partners/src/layouts/index.tsx
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/index.tsx
  sites/partners/src/pages/listings/[id]/applications/add.tsx
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/partners/src/pages/listings/[id]/applications/pending/index.tsx
  sites/partners/src/pages/listings/[id]/applications/resolved/index.tsx
  sites/partners/src/pages/listings/[id]/index.tsx
  sites/partners/src/pages/users/index.tsx
Labels: ready to merge, on hold

#699 fix: listings filtering UI bugs
  sites/public/src/components/listings/search/ListingsSearchModal.tsx
Labels: ready to merge

#715 fix: input font size to avoid mobile zoom
  doorway-ui-components/src/global/forms.scss
Labels: ready to merge

#623 fix: remove ability to edit close and lottery dates on a published listing
  api/src/services/listing.service.ts
  api/src/utilities/listings-utilities.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
Labels: ready to merge

#726 test: testing tests
  api/README.md
  api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
Labels: ready to merge

#724 feat: lottery status (released to partners / retracted) (bloom-housing#4167)
  api/prisma/migrations/14_add_lottery_status_enums/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-helpers/listing-factory.ts
  api/src/controllers/listing.controller.ts
  api/src/dtos/listings/listing-lottery-status.dto.ts
  api/src/dtos/listings/listing.dto.ts
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release

#725 feat: rerun and release lottery modals (#4166)
  sites/partners/__tests__/pages/listings/lottery.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/shared/ListingGuard.tsx
  sites/partners/src/pages/_error.tsx
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
  sites/partners/src/pages/users/index.tsx
  sites/partners/styles/lottery.module.scss
Labels: ready to merge, release

#728 fix: network error for password login
  sites/public/src/pages/sign-in.tsx
Labels: ready to merge

#729 fix: add post lottery button when lottery functionality is turned on
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/src/components/listings/ListingFormActions.tsx
Labels: ready to merge

#716 fix: remove do you work in
  doorway-ui-components/src/locales/es.json
  doorway-ui-components/src/locales/general.json
  doorway-ui-components/src/locales/tl.json
  doorway-ui-components/src/locales/vi.json
  doorway-ui-components/src/locales/zh.json
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/utilities/blankApplication.ts
  sites/partners/__tests__/pages/applications/index.test.tsx
  sites/partners/cypress/fixtures/alternateContactOnlyData.json
  sites/partners/cypress/fixtures/applicantOnlyData.json
  sites/partners/cypress/fixtures/application.json
  sites/partners/cypress/fixtures/demographicsOnlyData.json
  sites/partners/cypress/fixtures/emptyApplication.json
  sites/partners/cypress/fixtures/householdDetailsOnlyData.json
  sites/partners/cypress/fixtures/householdIncomeOnlyData.json
  sites/partners/cypress/fixtures/householdMemberOnlyData.json
  sites/partners/cypress/fixtures/partialApplicationA.json
  sites/partners/cypress/support/commands.js
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/applications/ApplicationsColDefs.ts
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsAddressColumns.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsMemberDrawer.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsPrimaryApplicant.tsx
  sites/partners/src/components/applications/PaperApplicationForm/FormMember.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
  sites/partners/src/lib/applications/FormTypes.ts
  sites/partners/src/lib/applications/formatApplicationData.ts
  sites/public/cypress/mockData/applicationData.ts
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/lib/applications/appAutofill.ts
  sites/public/src/pages/applications/contact/address.tsx
  sites/public/src/pages/applications/household/member.tsx
Labels: ready to merge

#733 fix: improve application submission logic (#4179)
  api/prisma/seed-helpers/listing-factory.ts
  api/src/services/application.service.ts
  api/test/integration/application.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/unit/services/application.service.spec.ts
  sites/public/src/pages/applications/review/summary.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
Labels: ready to merge, release

#730 feat: run lottery modals (#4168)
  api/prisma/seed-helpers/address-factory.ts
  shared-helpers/__tests__/testHelpers.ts
  sites/partners/__tests__/pages/applications/index.test.tsx
  sites/partners/__tests__/pages/listings/lottery.test.tsx
  sites/partners/__tests__/pages/settings/index.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/shared/NavigationHeader.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge, release

#732 fix: studio unit types in seed data
  api/prisma/seed-staging.ts
  sites/partners/cypress/fixtures/application.json
  sites/partners/cypress/fixtures/householdDetailsOnlyData.json
  sites/public/cypress/mockData/applicationData.ts
Labels: ready to merge, release

#738 release: use the correct error keys for State and Zip
  sites/public/src/pages/applications/contact/address.tsx
  sites/public/src/pages/applications/household/member.tsx
Labels: ready to merge

#735 feat: export lottery modal (#4176)
  sites/partners/__tests__/pages/listings/lottery.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge, release

#739 fix: filter ami charts by jurisdition (#4177)
  api/prisma/seed-staging.ts
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
Labels: ready to merge, release

#745 fix: update google analytics to use ga4 syntax
  sites/public/src/lib/customScripts.ts
  sites/public/src/pages/_app.tsx
Labels: ready to merge

#737 release: application confirmation styling updates based on design QA
  sites/public/src/pages/applications/review/confirmation.tsx
  sites/public/styles/overrides.scss
Labels: ready to merge, release

#741 feat: lottery partners experience (#4180)
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  shared-helpers/src/locales/general.json
  sites/partners/__tests__/pages/listings/lottery.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/pages/listings/[id]/lottery.tsx
  sites/partners/styles/lottery.module.scss
Labels: ready to merge, release

#718 fix: add hba jurisdiction data transfers
  api/package.json
  api/prisma/seed-staging.ts
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/data-transfer.dto.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  api/yarn.lock
  shared-helpers/src/utilities/formKeys.ts
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
Labels: ready to merge

#743 fix: availability type filter
  api/src/dtos/listings/listings-filter-params.dto.ts
  api/src/enums/listings/filter-availability-enum.ts
  api/src/enums/listings/filter-key-enum.ts
  api/src/services/listing.service.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  sites/public/src/components/listings/search/LandingSearch.tsx
  sites/public/src/components/listings/search/ListingsSearchModal.tsx
  sites/public/src/lib/listings/search.ts
Labels: ready to merge

#760 fix: monthly rent filter
  api/prisma/seed-helpers/unit-factory.ts
  api/prisma/seed-staging.ts
  api/src/services/listing.service.ts
Labels: ready to merge

#709 release: uptake of Seeds dialog and drawer
  shared-helpers/__tests__/Timeout.test.tsx
  shared-helpers/src/auth/Timeout.tsx
  shared-helpers/src/views/forgot-password/FormForgotPassword.tsx
  shared-helpers/src/views/sign-in/ResendConfirmationModal.tsx
  sites/partners/__mocks__/tabbable.js
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/e2e/default/06-admin-user-mangement.spec.ts
  sites/partners/cypress/e2e/default/08-preference-management.spec.ts
  sites/partners/src/components/applications/Aside.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsMemberDrawer.tsx
  sites/partners/src/components/applications/PaperApplicationForm/FormMember.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  sites/partners/src/components/listings/PaperListingDetails/DetailsUnitDrawer.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx
  sites/partners/src/components/listings/PaperListingForm/RequestChangesModal.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ListingPhotos.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
  sites/partners/src/components/settings/PreferenceDeleteModal.tsx
  sites/partners/src/components/settings/PreferenceDrawer.tsx
  sites/partners/src/components/users/FormUserManage.tsx
  sites/partners/src/pages/application/[id]/review.tsx
  sites/partners/src/pages/index.tsx
  sites/partners/src/pages/settings/index.tsx
  sites/partners/src/pages/users/index.tsx
  sites/partners/styles/overrides.scss
  sites/public/src/components/account/ConfirmationModal.tsx
  sites/public/src/components/listing/GetApplication.tsx
  sites/public/src/components/listings/search/LandingSearch.tsx
  sites/public/src/components/listings/search/ListingsSearchModal.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
  sites/public/src/pages/create-account.tsx
  sites/public/src/pages/verify.tsx
  sites/public/styles/overrides.scss
Labels: ready to merge, release

#763 Release: application export catch up doorway
  api/prisma/migrations/13_application_lottery_positioning/migration.sql
  api/prisma/migrations/15_lottery_position_id/migration.sql
  api/prisma/schema.prisma
  api/src/controllers/application.controller.ts
  api/src/controllers/lottery.controller.ts
  api/src/dtos/applications/application-lottery-position.dto.ts
  api/src/dtos/applications/application-update.dto.ts
  api/src/dtos/applications/application.dto.ts
  api/src/modules/app.module.ts
  api/src/modules/lottery.module.ts
  api/src/services/application-csv-export.service.ts
  api/src/services/listing.service.ts
  api/src/services/lottery.service.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/unit/services/application-csv-export.service.spec.ts
  api/test/unit/services/application.service.spec.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  shared-helpers/src/auth/AuthContext.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge, release

#757 feat: lottery opt in, retract (release)
  api/prisma/migrations/15_lottery_opt_in/migration.sql
  api/prisma/schema.prisma
  api/src/dtos/listings/listing.dto.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/pages/listings/lottery.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/components/shared/NavigationHeader.module.scss
  sites/partners/src/lib/listings/AdditionalMetadataFormatter.ts
  sites/partners/src/lib/listings/BooleansFormatter.ts
  sites/partners/src/lib/listings/formTypes.ts
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/partners/src/pages/listings/[id]/applications/pending/index.tsx
  sites/partners/src/pages/listings/[id]/index.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge, release

#761 fix: ensure mutually-exclusive "none" option for Vouchers question
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/pages/applications/financial/vouchers.tsx
Labels: ready to merge

#766 fix: monthly rent seed data
  api/prisma/seed-helpers/unit-factory.ts
Labels: bug, ready to merge

#762 fix: swap lingering UIC Modal for Seeds Dialog
  sites/partners/src/components/users/FormUserConfirm.tsx
  sites/partners/src/components/users/ReRequestConfirmation.tsx
Labels: ready to merge, release

#768 fix: programs and preference null check
  api/src/services/application-csv-export.service.ts
Labels: ready to merge

#765 release: lottery expiration frontend and cron job (#4184)
  .github/workflows/cypress_partners.yml
  .github/workflows/integration_tests.yml
  .github/workflows/unit_tests_api.yml
  api/.env.template
  api/prisma/seed-helpers/listing-factory.ts
  api/src/controllers/listing.controller.ts
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/.env.template
  sites/partners/__tests__/pages/listings/lottery.test.tsx
  sites/partners/next.config.js
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/pages/listings/[id]/lottery.tsx
  sites/partners/styles/lottery.module.scss
Labels: ready to merge, release

#776 fix: availability filter
  api/src/services/listing.service.ts
Labels: ready to merge
