Repository metrotranscom/doorway, pull requests merged in 2024-06, with the labels that each got.

#661 Release: script runner for doorway
  .github/workflows/unit_tests_api.yml
  api/.env.template
  api/prisma/migrations/11_add_script_runs/migration.sql
  api/prisma/schema.prisma
  api/src/controllers/auth.controller.ts
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/data-transfer.dto.ts
  api/src/modules/app.module.ts
  api/src/modules/script-runner.module.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/app.service.spec.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#659 fix: content fixes
  shared-helpers/src/locales/general.json
  sites/partners/page_content/locale_overrides/general.json
Labels: ready to merge

#663 docs: release - updated pr template (#4116)
  docs/pull_request_template.md
Labels: ready to merge

#642 fix: demographic spoken language bugs
  api/src/dtos/applications/demographic.dto.ts
  api/src/services/application-csv-export.service.ts
  api/src/services/application.service.ts
  api/test/integration/application.e2e-spec.ts
  api/test/integration/permission-tests/helpers.ts
  api/test/unit/services/application.service.spec.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormDemographics.tsx
  sites/partners/src/lib/applications/FormTypes.ts
  sites/public/src/pages/applications/review/demographics.tsx
Labels: ready to merge

#669 fix: office hours in email template
  api/src/views/confirmation.hbs
Labels: ready to merge

#654 fix: release - update password requirements (#4107)
  api/prisma/seed-dev.ts
  api/prisma/seed-helpers/user-factory.ts
  api/prisma/seed-staging.ts
  api/src/utilities/password-regex.ts
  api/test/integration/ami-chart.e2e-spec.ts
  api/test/integration/application-flagged-set.e2e-spec.ts
  api/test/integration/application.e2e-spec.ts
  api/test/integration/asset.e2e-spec.ts
  api/test/integration/auth.e2e-spec.ts
  api/test/integration/jurisdiction.e2e-spec.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/multiselect-question.e2e-spec.ts
  api/test/integration/permission-tests/helpers.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/integration/reserved-community-type.e2e-spec.ts
  api/test/integration/unit-accessibility-priority-type.e2e-spec.ts
  api/test/integration/unit-rent-type.e2e-spec.ts
  api/test/integration/unit-type.e2e-spec.ts
  api/test/integration/user.e2e-spec.ts
  api/test/unit/passports/mfa.strategy.spec.ts
  api/test/unit/passports/single-use-code.strategy.spec.ts
  api/test/unit/services/auth.service.spec.ts
  api/test/unit/services/user.service.spec.ts
  api/test/unit/utilities/password-helper.spec.ts
  api/test/unit/utilities/password-regex.spec.ts
  shared-helpers/index.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/utilities/passwordRegex.ts
  sites/partners/cypress/e2e/default/02-mfa.spec.ts
  sites/partners/cypress/fixtures/jurisdictionalAdmin.json
  sites/partners/cypress/fixtures/jurisdictionalAdminUser.json
  sites/partners/cypress/fixtures/termsUnacceptedUser.json
  sites/partners/src/components/users/FormUserConfirm.tsx
  sites/public/src/pages/account/edit.tsx
  sites/public/src/pages/create-account.tsx
  sites/public/src/pages/reset-password.tsx
  sites/public/src/pages/sign-in.tsx
Labels: ready to merge

#671 fix: use default value for accept TOS checkbox
  sites/public/src/pages/create-account.tsx
Labels: ready to merge

#674 fix: include check for address type (#4136)
  sites/public/src/components/listing/ListingView.tsx
Labels: ready to merge

#681 fix: hide do you work question
  sites/public/cypress/e2e/pages/application/contact/address.spec.ts
  sites/public/cypress/e2e/pages/application/household/member.spec.ts
  sites/public/cypress/support/commands.js
  sites/public/src/pages/applications/contact/address.tsx
  sites/public/src/pages/applications/household/member.tsx
Labels: ready to merge

#682 fix: looser isUserSiteMatch (#4120)
  api/.env.template
  api/src/services/user.service.ts
  api/test/unit/services/user.service.spec.ts
Labels: ready to merge

#683 fix: fallback and refresh translations (#4105)
  api/prisma/migrations/12_add_content_updated_at/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-staging.ts
  api/src/dtos/listings/listing.dto.ts
  api/src/services/listing.service.ts
  api/src/services/translation.service.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/translation.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#676 release: fix buttons and other elements from design QA
  sites/partners/src/components/listings/PaperListingDetails/DetailsUnitDrawer.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ListingPhotos.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
  sites/partners/src/components/settings/PreferenceDrawer.tsx
  sites/partners/src/pages/application/[id]/review.tsx
Labels: ready to merge

#680 fix: allow removal of mailing address
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/lib/listings/AdditionalMetadataFormatter.ts
  sites/partners/src/lib/listings/BooleansFormatter.ts
  sites/partners/src/pages/listings/[id]/index.tsx
  sites/public/__tests__/testUtils.tsx
Labels: ready to merge

#693 fix: add language to headers (#4148)
  sites/public/src/pages/preview/listings/[id].tsx
Labels: 1 review needed

#697 fix: move ts-node to dependencies
  api/package.json
Labels: ready to merge

#700 fix: add missing listing translations
  api/src/services/translation.service.ts
  api/test/unit/services/translation.service.spec.ts
Labels: ready to merge

#703 fix: new translations for housing vouchers
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
Labels: ready to merge

#705 feat: ami chart import script runner (#4125)
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/ami-chart-import.dto.ts
  api/src/modules/script-runner.module.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#702 fix: update create call
  api/src/services/user.service.ts
  api/test/unit/services/user.service.spec.ts
Labels: ready to merge

#708 fix: update backend docker
  build/docker/Dockerfile.backend
Labels: ready to merge

#706 feat: lottery toggle and empty state (#4043)
  build/docker/Dockerfile.sites-generic
  ci/buildspec/build_partners.yml
  sites/partners/.env.template
  sites/partners/next.config.js
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/shared/NavigationHeader.tsx
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/partners/src/pages/listings/[id]/applications/pending/index.tsx
  sites/partners/src/pages/listings/[id]/index.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
  sites/partners/styles/lottery.module.scss
Labels: ready to merge, release

#710 fix: remove view listing button from closed listings
  sites/public/__tests__/components/applications/StatusItem.test.tsx
  sites/public/src/components/account/StatusItem.tsx
  sites/public/src/pages/account/StatusItemWrapper.tsx
Labels: ready to merge

#707 feat: add application confirmation modals (#4154)
  api/README.md
  api/prisma/migrations/13_add_lottery_last_run_at/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-helpers/address-factory.ts
  api/prisma/seed-helpers/household-member-factory.ts
  api/prisma/seed-staging.ts
  api/src/dtos/listings/listing.dto.ts
  api/test/unit/services/email.service.spec.ts
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/package.json
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/pages/applications/index.test.tsx
  sites/partners/__tests__/pages/listings/index.test.tsx
  sites/partners/__tests__/testUtils.tsx
  sites/partners/jest.config.js
  sites/partners/package.json
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/public/package.json
  yarn.lock
Labels: ready to merge, release

#714 fix: lottery rebase issues (#4162)
  sites/partners/src/components/shared/NavigationHeader.tsx
  sites/public/package.json
  yarn.lock
Labels: ready to merge, release

#711 feat: login with v3 recaptcha (#4091)
  .circleci/config.yml
  .github/workflows/unit_tests_api.yml
  api/.env.template
  api/package.json
  api/src/controllers/auth.controller.ts
  api/src/dtos/auth/login.dto.ts
  api/src/passports/single-use-code.strategy.ts
  api/src/services/auth.service.ts
  api/src/services/user.service.ts
  api/test/integration/user.e2e-spec.ts
  api/test/jest-with-coverage.config.js
  api/test/unit/passports/single-use-code.strategy.spec.ts
  api/test/unit/services/auth.service.spec.ts
  api/test/unit/services/user.service.spec.ts
  api/yarn.lock
  shared-helpers/src/auth/AuthContext.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/views/sign-in/FormSignInDefault.tsx
  shared-helpers/src/views/sign-in/FormSignInPwdless.tsx
  sites/partners/.env.template
  sites/partners/__tests__/pages/settings/index.test.tsx
  sites/partners/next.config.js
  sites/partners/package.json
  sites/partners/src/lib/users/signInHelpers.ts
  sites/partners/src/pages/_app.tsx
  sites/partners/src/pages/sign-in.tsx
  sites/public/.env.template
  sites/public/cypress/e2e/pages/my-applications.spec.ts
  sites/public/cypress/support/commands.js
  sites/public/next.config.js
  sites/public/src/pages/_app.tsx
  sites/public/src/pages/listings.tsx
  sites/public/src/pages/sign-in.tsx
  sites/public/src/pages/verify.tsx
Labels: ready to merge, release
