Repository metrotranscom/doorway, pull requests merged in 2025-02, with the labels that each got.

#1071 feat: 100 admin users in the dev environment for perf testing
  api/prisma/seed-staging.ts
Labels: question

#1062 release: refactor and extend zip code (#4588)
  api/src/controllers/application.controller.ts
  api/src/controllers/lottery.controller.ts
  api/src/services/application-exporter.service.ts
  api/src/utilities/zip-export.ts
  api/test/unit/services/application-exporter.service.spec.ts
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/api/adapter/[...backendUrl].ts
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge, release

#1077 fix: wait for map load
  sites/public/src/components/listings/ListingsCombined.module.scss
  sites/public/src/components/listings/ListingsCombined.tsx
  sites/public/src/components/listings/ListingsMap.tsx
  sites/public/src/components/listings/MapClusterer.tsx
  sites/public/src/components/listings/search/ListingsSearchCombined.tsx
  sites/public/src/components/shared/MapRecenter.tsx
  sites/public/src/pages/listings.tsx
Labels: ready to merge

#1041 release: don't show lottery dates when open waitlist is selected (#4522)
  sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/partners/src/lib/listings/AdditionalMetadataFormatter.ts
  sites/partners/src/lib/listings/BooleansFormatter.ts
  sites/partners/src/lib/listings/EventsFormatter.ts
Labels: ready to merge

#1083 fix: updating reset translations from bash
  api/src/services/script-runner.service.ts
Labels: high priority, ready to merge

#1081 fix: null checks in minMax process (#4632)
  api/src/utilities/unit-utilities.ts
Labels: ready to merge, release

#1079 fix: change the from email for gov delivery sends
  api/src/services/email.service.ts
Labels: ready to merge

#1085 fix: update how csv generates preferences
  api/src/services/application-exporter.service.ts
  api/src/utilities/application-export-helpers.ts
Labels: ready to merge

#1057 fix: replaces errors.leasingAgentAddress with errors.listingsLeasingA…
  sites/partners/src/components/listings/PaperListingForm/sections/LeasingAgent.tsx
Labels: ready to merge

#1082 feat: paginating public user transfer
  api/src/dtos/script-runner/data-transfer.dto.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#1089 fix: autofill bug
  sites/public/src/pages/applications/start/autofill.tsx
Labels: ready to merge

#1093 fix: occupancy issues
  shared-helpers/__tests__/occupancyFormatting.test.tsx
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/views/occupancyFormatting.tsx
Labels: ready to merge, release

#1092 refactor: max width layout (#4500)
  sites/public/src/layouts/max-width.module.scss
  sites/public/src/layouts/max-width.tsx
  sites/public/src/pages/404.tsx
  sites/public/src/pages/_error.tsx
Labels: ready to merge, release

#1096 fix: pagination fix for desktop view
  sites/public/src/components/listings/search/ListingsSearchCombined.tsx
Labels: ready to merge
