Repository metrotranscom/doorway, pull requests merged in 2025-05, with the labels that each got.

#1228 fix: remove extra map fetch on desktop, mobile
  sites/public/cypress/e2e/pages/listings-map.spec.ts
  sites/public/src/components/listings/ListingsMap.tsx
  sites/public/src/components/listings/Pagination.tsx
  sites/public/src/components/listings/search/ListingsSearchCombined.tsx
  sites/public/src/components/shared/MapControl.tsx
  sites/public/src/components/shared/MapRecenter.tsx
Labels: ready to merge

#1241 fix: site message updates
  build/docker/Dockerfile.sites-generic
  ci/buildspec/build_public.yml
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/views/layout/AlertBanner.tsx
  sites/public/.env.template
  sites/public/next.config.js
  sites/public/src/layouts/application.tsx
Labels: ready to merge

#1231 fix: combined listings and mapmarkers endpoint optimizations
  api/prisma/migrations/26_update_combined_listing/migration.sql
  api/prisma/migrations/27_map_marker_view/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-helpers/address-factory.ts
  api/prisma/seed-staging.ts
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  sites/public/cypress.config.ts
Labels: 1 review needed

#1260 fix: add required docker variables for secure download
  build/docker/Dockerfile.sites-generic
  ci/buildspec/build_partners.yml
Labels: ready to merge

#1259 fix: missing additional questions translation string
  sites/public/src/tsx_content/questions-cards.tsx
Labels: bug, ready to merge
