Repository metrotranscom/doorway, pull requests merged in 2025-03, with the labels that each got.

#1103 fix: oval icons
  sites/public/src/components/listings/ListingsCombined.module.scss
  sites/public/src/components/listings/MapClusterer.tsx
Labels: ready to merge

#1097 Release: 2025-02-20
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/package.json
  shared-helpers/src/auth/AuthContext.ts
  shared-helpers/src/locales/general.json
  sites/partners/__tests__/forgot-password.test.tsx
  sites/partners/__tests__/pages/application/index.test.tsx
  sites/partners/__tests__/pages/listings/[id]/index.test.tsx
  sites/partners/__tests__/pages/listings/applications/index.test.tsx
  sites/partners/__tests__/pages/reset-password.test.tsx
  sites/partners/__tests__/pages/users/terms.test.tsx
  sites/partners/__tests__/testUtils.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsAlternateContact.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationAddress.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailPreferences.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailPrograms.tsx
  sites/partners/src/pages/application/[id]/index.tsx
Labels: ready to merge

#1099 release: user favorite listings (#4658)
  api/prisma/migrations/24_user_favorite_listings/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-helpers/user-factory.ts
  api/src/controllers/user.controller.ts
  api/src/dtos/users/user-favorite-listing.dto.ts
  api/src/dtos/users/user.dto.ts
  api/src/enums/shared/modification-enum.ts
  api/src/services/user.service.ts
  api/test/integration/user.e2e-spec.ts
  api/test/unit/services/user.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release

#1111 feat: add dependabot yaml
  .github/dependabot.yml
Labels: ready to merge

#1110 fix: multiple admin accounts
  ci/buildspec/migrate_stop_backend.yml
Labels: 1 review needed

#1154 fix: language not persisting through navigation
  doorway-ui-components/package.json
  doorway-ui-components/src/page_components/listing/ListingCard.tsx
  sites/public/src/components/listings/ListingsList.tsx
  sites/public/src/components/listings/search/LandingSearch.tsx
Labels: ready to merge

#1165 fix: community type - tay
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
Labels: ready to merge

#1167 fix: flaky test updates (#4743)
  api/test/integration/listing.e2e-spec.ts
Labels: ready to merge, release

#1166 fix: update to fix pop up translations
  api/src/services/listing.service.ts
Labels: 1 review needed

#1168 Feat/cookiefix
  api/src/services/auth.service.ts
Labels: ready to merge

#1169 Feat/cookiefix
  api/src/services/auth.service.ts
Labels: ready to merge

#1170 Feat/cookiefix
  api/src/services/auth.service.ts
Labels: ready to merge
