Repository metrotranscom/doorway, pull requests merged in 2025-07, with the labels that each got.

#1365 fix: uptaking uic change
  doorway-ui-components/package.json
  shared-helpers/package.json
  sites/partners/package.json
  sites/public/package.json
  yarn.lock
Labels: 1 review needed

#1346 feat: portal of origin field (#4997)
  api/prisma/migrations/26_was_created_externally/migration.sql
  api/prisma/schema.prisma
Labels: ready to merge, release

#1369 feat: portal of origin script
  api/src/controllers/script-runner.controller.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#1356 feat: add unit groups unit types to paper form (#5000)
  sites/partners/__tests__/components/applications/sections/FormHouseholdDetails.test.tsx
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
Labels: ready to merge, release

#1360 refactor: fetch less data in partner user drawer (#5014)
  api/src/enums/listings/view-enum.ts
  api/src/services/listing.service.ts
  api/test/unit/services/listing.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/users/index.tsx
Labels: ready to merge, release

#1188 fix: add tay community type to email
  api/src/services/email.service.ts
Labels: ready to merge

#1359 docs: update readme (#4538)
  README.md
Labels: ready to merge, release

#1372 fix: site footer rtl (#5010)
  sites/public/src/components/shared/CustomSiteFooter.module.scss
Labels: ready to merge, release

#712 fix: ami import formatting instructions (#4163)
  api/src/services/script-runner.service.ts
Labels: ready to merge, release

#1373 fix: update unit groups displayed if needed (#5037)
  shared-helpers/__tests__/unitTypes.test.ts
  shared-helpers/src/utilities/unitTypes.ts
  sites/partners/__tests__/components/applications/sections/FormHouseholdDetails.test.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
  sites/public/__tests__/pages/account/application/[id]/index.test.tsx
  sites/public/src/components/applications/SubmittedApplicationView.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/lib/applications/ApplicationConductor.ts
  sites/public/src/lib/applications/PreferredUnitSizeStep.ts
  sites/public/src/lib/helpers.tsx
  sites/public/src/pages/applications/review/summary.tsx
  sites/public/src/pages/applications/start/autofill.tsx
Labels: ready to merge, release

#1389 feat: api partners full time student paper application questions
  api/prisma/migrations/27_add_full_time_student_fields/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-staging.ts
  api/src/dtos/applications/applicant.dto.ts
  api/src/dtos/applications/household-member.dto.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  api/src/services/application-exporter.service.ts
  api/src/services/application.service.ts
  api/src/utilities/application-export-helpers.ts
  api/test/unit/services/application-exporter.service.spec.ts
  api/test/unit/services/application.service.spec.ts
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/src/locales/general.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/utilities/blankApplication.ts
  sites/partners/__tests__/components/applications/sections/FormHouseholdDetails.test.tsx
  sites/partners/__tests__/components/applications/sections/FormHouseholdMembers.test.tsx
  sites/partners/__tests__/components/applications/sections/FormPrimaryApplicant.test.tsx
  sites/partners/__tests__/pages/application/index.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/applications/ApplicationsColDefs.ts
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsMemberDrawer.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdDetails.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsPrimaryApplicant.tsx
  sites/partners/src/components/applications/PaperApplicationForm/FormMember.tsx
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/lib/applications/FormTypes.ts
  sites/partners/src/lib/applications/formatApplicationData.ts
  sites/partners/src/pages/application/[id]/index.tsx
  sites/partners/src/pages/listings/[id]/applications/index.tsx
Labels: ready to merge, release

#1380 feat: bash fixes 1 (#5104)
  shared-helpers/src/utilities/photos.ts
  sites/public/__tests__/components/listing/listing_sections/Apply.test.tsx
  sites/public/src/components/listing/ListingView.tsx
  sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
  sites/public/src/components/listing/listing_sections/Apply.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
Labels: ready to merge, release

#1239 fix: less likely to flood the connection pools
  api/src/services/script-runner.service.ts
Labels: ready to merge

#1383 fix: flaky map cypress test
  sites/public/cypress.config.ts
  sites/public/cypress/e2e/pages/listings-map.spec.ts
Labels: ready to merge
