Repository metrotranscom/doorway, pull requests merged in 2025-01, with the labels that each got.

#1026 fix: use correct ami percentage in csv
  api/src/services/listing-csv-export.service.ts
Labels: ready to merge

#1030 fix: household member delete + order (#4510)
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
Labels: ready to merge, release

#976 release: export lottery with sorted preferences by ordinal
  api/src/services/application-exporter.service.ts
  api/test/unit/services/application-exporter.service.spec.ts
Labels: ready to merge

#1033 fix: always deploy internal api
  ci/buildspec/update_ecs.yml
Labels: ready to merge

#1036 fix: Jurisdictional Admin - No PII account emails
  api/src/services/listing.service.ts
  api/src/services/user.service.ts
  api/test/unit/services/listing.service.spec.ts
Labels: bug, ready to merge

#1000 fix: community type disclaimer
  api/prisma/migrations/21_community_type_description/migration.sql
  api/prisma/schema.prisma
  api/src/dtos/listings/listing.dto.ts
  api/src/services/translation.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/unit/services/translation.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/fixtures/listing.json
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailCommunityType.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/CommunityType.tsx
  sites/partners/src/lib/listings/AdditionalMetadataFormatter.ts
  sites/partners/src/lib/listings/BooleansFormatter.ts
  sites/partners/src/lib/listings/formTypes.ts
  sites/public/src/lib/applications/AppSubmissionContext.ts
  sites/public/src/lib/applications/ApplicationConductor.ts
  sites/public/src/pages/applications/start/community-disclaimer.tsx
  sites/public/src/pages/applications/start/what-to-expect.tsx
Labels: ready to merge, release

#1001 fix: add gap to side panel list item
  sites/public/src/components/account/ApplicationsView.module.scss
Labels: ready to merge

#1003 release: feature flag script
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/feature-flags/feature-flag-create.dto.ts
  api/src/dtos/feature-flags/feature-flag-update.dto.ts
  api/src/modules/script-runner.module.ts
  api/src/services/script-runner.service.ts
  api/test/integration/feature-flag.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/unit/services/feature-flag.service.spec.ts
  api/test/unit/services/script-runner.service.spec.ts
  build/docker/Dockerfile.sites-generic
  ci/buildspec/build_partners.yml
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/.env.template
  sites/partners/next.config.js
Labels: ready to merge, release

#1039 release: remove unused email logic (#4526)
  api/src/services/email.service.ts
  api/src/services/user.service.ts
  api/src/views/portal-account-update.hbs
Labels: ready to merge, release

#1034 fix: empty input script runner
  api/src/controllers/script-runner.controller.ts
  api/src/services/script-runner.service.ts
Labels: ready to merge

#1013 fix: switch bulk emails to individual email sends
  api/.env.template
  api/package.json
  api/prisma/seed-helpers/translation-factory.ts
  api/src/main.ts
  api/src/modules/email.module.ts
  api/src/services/email.service.ts
  api/src/services/listing.service.ts
  api/src/services/lottery.service.ts
  api/src/services/user.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/integration/user.e2e-spec.ts
  api/test/unit/services/email.service.spec.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  api/test/unit/services/user.service.spec.ts
  api/yarn.lock
  sites/public/cypress/e2e/pages/submit-application.spec.ts
Labels: 1 review needed

#1043 fix: add null check for csv export
  api/src/services/application-exporter.service.ts
  api/src/services/email.service.ts
  api/src/utilities/application-export-helpers.ts
  sites/partners/src/pages/application/[id]/edit.tsx
Labels: ready to merge

#1047 release: include preference address (#4537)
  api/src/utilities/application-export-helpers.ts
Labels: ready to merge, release

#990 feat: property name search
  api/src/dtos/shared/base-filter.dto.ts
  api/src/services/listing.service.ts
  doorway-ui-components/src/forms/Field.scss
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  sites/public/src/components/listings/search/LandingSearch.module.scss
  sites/public/src/components/listings/search/LandingSearch.tsx
  sites/public/src/components/listings/search/ListingsSearchCombined.tsx
  sites/public/src/components/listings/search/ListingsSearchModal.tsx
  sites/public/src/components/listings/search/ListingsSearchModalDeprecated.tsx
  sites/public/src/lib/listings/listing-query-builder.ts
  sites/public/src/lib/listings/search.ts
Labels: ready to merge

#1054 fix: switch to Link component from Seeds on forgot password
  shared-helpers/src/views/sign-in/FormSignIn.module.scss
  shared-helpers/src/views/sign-in/FormSignInDefault.tsx
  shared-helpers/src/views/sign-in/FormSignInPwdless.tsx
Labels: ready to merge

#1060 fix: app submission edge cases (#4550)
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/pages/applications/review/terms.tsx
Labels: ready to merge, release

#1048 release: clear household members for Submit & New in Applications (#4535)
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
Labels: ready to merge

#1066 fix: set studio + sro to zero bedrooms (#4611)
  sites/partners/src/lib/listings/UnitsFormatter.ts
Labels: ready to merge, release

#1070 fix: search field without flag
  sites/public/src/components/listings/search/ListingsSearchModalDeprecated.tsx
Labels: ready to merge

#1073 refactor: update sizes of clusters
  sites/public/src/components/listings/MapClusterer.tsx
Labels: ready to merge

#1069 feat: move recenter button to map
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/components/listings/ListingsCombined.module.scss
  sites/public/src/components/listings/ListingsCombined.tsx
  sites/public/src/components/listings/ListingsList.tsx
  sites/public/src/components/listings/ListingsMap.tsx
  sites/public/src/components/shared/MapControl.module.scss
  sites/public/src/components/shared/MapRecenter.module.scss
  sites/public/src/components/shared/MapRecenter.tsx
  sites/public/styles/overrides.scss
Labels: ready to merge

#1064 release: update translations and sign in link for lottery email (#4506)
  api/prisma/seed-helpers/translation-factory.ts
  api/src/controllers/script-runner.controller.ts
  api/src/services/email.service.ts
  api/src/services/script-runner.service.ts
  api/src/views/lottery-published-applicant.hbs
  api/test/unit/services/email.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge
