Repository metrotranscom/doorway, pull requests merged in 2025-04, with the labels that each got.

#1187 feat: alameda count is ON
  shared-helpers/src/utilities/formKeys.ts
Labels: high priority, ready to merge

#1190 Removing alameda ref
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingDetails.tsx
Labels: ready to merge

#1147 feat: creating new listing image asset transfer script
  api/prisma/migrations/24_temp_listing_map/migration.sql
  api/prisma/schema.prisma
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/asset-transfer.dto.ts
  api/src/modules/script-runner.module.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: 1 review needed

#1101 Release 02-26-2025
  api/prisma/migrations/25_unit_groups_add_created_updated_at/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-staging.ts
  api/src/decorators/validate-units-required.decorator.ts
  api/src/dtos/listings/listing-published-update.dto.ts
  api/src/dtos/listings/listing-update.dto.ts
  api/src/dtos/listings/listing.dto.ts
  api/src/dtos/unit-groups/unit-group-ami-level-create.dto.ts
  api/src/dtos/unit-groups/unit-group-ami-level.dto.ts
  api/src/dtos/unit-groups/unit-group-create.dto.ts
  api/src/dtos/unit-groups/unit-group.dto.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  api/src/services/listing-csv-export.service.ts
  api/src/services/listing.service.ts
  api/src/utilities/feature-flag-utilities.ts
  api/src/utilities/unit-utilities.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/utilities/unit-utilities.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/settings/PreferenceEditModal.tsx
  sites/partners/src/pages/settings/index.tsx
Labels: ready to merge, release

#1206 fix: all users now transfered
  api/src/services/script-runner.service.ts
Labels: ready to merge

#1218 fix: adding order by to paginated scripts
  api/src/services/script-runner.service.ts
Labels: high priority, ready to merge

#1215 4592/secure app and lottery exports 2
  api/.env.template
  api/package.json
  api/src/controllers/application.controller.ts
  api/src/controllers/lottery.controller.ts
  api/src/services/application-exporter.service.ts
  api/src/utilities/s3-helpers.ts
  api/src/utilities/zip-export.ts
  api/yarn.lock
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/.env.template
  sites/partners/next.config.js
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: high priority, ready to merge

#1225 Revert "Release 02-26-2025 (#1101)"
  api/prisma/migrations/25_unit_groups_add_created_updated_at/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-staging.ts
  api/src/decorators/validate-units-required.decorator.ts
  api/src/dtos/listings/listing-published-update.dto.ts
  api/src/dtos/listings/listing-update.dto.ts
  api/src/dtos/listings/listing.dto.ts
  api/src/dtos/unit-groups/unit-group-ami-level-create.dto.ts
  api/src/dtos/unit-groups/unit-group-ami-level.dto.ts
  api/src/dtos/unit-groups/unit-group-create.dto.ts
  api/src/dtos/unit-groups/unit-group.dto.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  api/src/services/listing-csv-export.service.ts
  api/src/services/listing.service.ts
  api/src/utilities/feature-flag-utilities.ts
  api/src/utilities/unit-utilities.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/utilities/unit-utilities.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/settings/PreferenceEditModal.tsx
  sites/partners/src/pages/settings/index.tsx
Labels: ready to merge
